export const SET_LOGININFO = 'SET_LOGININFO'
export const SET_ENTRY = 'SET_ENTRY'
export const SET_ROUTERTAGS = 'SET_ROUTERTAGS'
export const CLEAR_ROUTERTAGS = 'CLEAR_ROUTERTAGS'
export const REMOVE_ROUTERTAGS = 'REMOVE_ROUTERTAGS'
export const SET_FULL = 'SET_FULL'
export const SET_INSDATA = 'SET_INSDATA'
export const SET_GAMETYPEDATA = 'SET_GAMETYPEDATA'
export const GET_MSGWEBSOCKET = 'GET_MSGWEBSOCKET'
export const SET_FONTSIZE = 'SET_FONTSIZE'
export const SET_MENUDATA = 'SET_MENUDATA'


